# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bcb8e0b494ae45ff10e7a0f3e033f35d4c442c1f6f8335d5b3c88c6ee690df26f979a1107e55a70a8ab2d7d45dbb93a31ddd5a2780f59faa22b11306759921a

test:
  secret_key_base: 20e7e256c22b89f079e567db1b97be6c29c9505b5c9b15b8307f2149d6dfeb8d15096359cd3e02def89059ca850365c4f7704904de446075a11d7d71c6329aa9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
